embeddings {
  tensor_path: "https://raw.githubusercontent.com/arioncheong/finance-lexicon/main/vectors_100d.tsv"
  metadata_path: "https://raw.githubusercontent.com/arioncheong/finance-lexicon/main/metadata.tsv"
}
